version: "3"

services:
    nginx:
        # container_name: nginx
        build:
            context: .
            dockerfile: infra/images/nginx/Dockerfile
        volumes: 
            - ./app/:/var/www/app/
        ports: 
            - 80:80
        restart: always
        networks:
            - App
    
    php:
        # container_name: php
        build:
            context: .
            dockerfile: ./infra/images/php/Dockerfile
        depends_on:
            - mysql
        environment:
            APP_ENV: dev
        volumes:
            - ./app/:/var/www/app/
        restart: always
        networks:
            - App 

    nodejs:
        # container_name: nodejs
        build:
            context: .
            dockerfile: ./infra/images/nodejs/Dockerfile
        volumes:
          - ./app/:/var/www/app/
        command: "bash -ci 'yarn install'"
        restart: "no"

###> symfony/mailer ###
    mailer:
        # container_name: mailer
        image: tophfr/mailcatcher
        ports: 
            - 1025:25
            - 1080:80
        restart: always
        networks:
            - App
###< symfony/mailer ###
    
    mysql:
        # container_name: mysql
        image: mysql:8.0.26
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
        ports:
            - 3306:3306
        volumes:
            - ./infra/volumes/database:/var/lib/mysql
        environment:
            # MYSQL_USER: user
            # MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: App
        restart: always
        networks:
            - App

networks:
    App:
